#!/bin/sh
# Send the informations to Event Browser (gedq)
#
# --- Input arguments from snmptt
#       arg1    $HOSTNAME$
#       arg2    $SERVICEDESC$
#       arg3    $SERVICESTATE$
#       arg4    $SERVICEOUTPUT$
#       arg5    $HOSTADDRESS$
#       arg6    $HOSTALIAS$
#       arg7    $HOSTGROUPS$
#       arg8    $SERVICEGROUPS$

bin="/srv/eyesofnetwork/ged/bin/gedq"

case "$3" in
  INFORMATION|INFORMATIONAL)
	$bin -push -type 2 "$1" "$2" 0 "" "$4" "$5" "$6" "$7" "$8" 
        ;;
  WARNING|MINOR)
        $bin -push -type 2 "$1" "$2" 1 "" "$4" "$5" "$6" "$7" "$8"
        ;;
  CRITICAL|MAJOR|SERIOUS)
	$bin -push -type 2 "$1" "$2" 2 "" "$4" "$5" "$6" "$7" "$8"
        ;;
  *)
	$bin -push -type 2 "$1" "$2" 3 "" "$4" "$5" "$6" "$7" "$8"
	exit 1
esac

exit 0
