#!/bin/sh
# Send the informations to Event Browser (gedq)
#
# --- Input arguments
# 	arg1	$HOSTNAME$
#	arg2	$SERVICEDESC$ 
#	arg3	$HOSTSTATE$ 
#	arg4	$HOSTOUTPUT$
#	arg5	$HOSTADDRESS$
#	arg6	$HOSTALIAS$
#	arg7	$HOSTGROUPS$

bin="/srv/eyesofnetwork/ged/bin/gedq"

case "$3" in
  UP)
        $bin -push -type 1 "$1" "HOST UP" 0 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$1" "HOST UP" 0
        $bin -drop -type 1 "$1" "HOST DOWN" 2
        $bin -drop -type 1 "$1" "HOST UNREACHABLE" 2
        $bin -drop -type 1 "$1" "UNKNOWN" 3 
        ;;
  DOWN)
        $bin -push -type 1 "$1" "HOST DOWN" 2 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$1" "HOST UP" 0
        $bin -drop -type 1 "$1" "HOST UNREACHABLE" 2
        $bin -drop -type 1 "$1" "UNKNOWN" 3 
        ;;
  UNREACHABLE)
        $bin -push -type 1 "$1" "HOST UNREACHABLE" 2 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$1" "HOST UP" 0
        $bin -drop -type 1 "$1" "HOST DOWN" 2
        $bin -drop -type 1 "$1" "UNKNOWN" 3 
        ;;
  *)
        $bin -push -type 1 "$1" "UNKNOWN" 3 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$1" "HOST UP" 0
        $bin -drop -type 1 "$1" "HOST DOWN" 2
        $bin -drop -type 1 "$1" "HOST UNREACHABLE" 2
        exit 1
esac

exit 0


